[torch-frontend]add canonicalize for ccl.collectives
bytedance/byteir pull request #128
Opened 2024-02-26 15:21 UTC by linuxlonelyeagle

2024-02-26 15:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bytedance/byteir?pullRequest=128) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bytedance/byteir?pullRequest=128) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bytedance/byteir?pullRequest=128) it.</sub>

2024-02-26 16:34 UTC, qingyunqu requested changes

2024-02-26 16:34 UTC, qingyunqu commented on compiler/dialects/lib/Dialect/Ccl/IR/CclOps.cpp
> +struct EliminateUnnecessaryWait : public OpRewritePattern<BroadcastOp> {
add lit test?

2024-03-13 03:20 UTC, Vremold requested changes
LGTM overall. Just a few comments.

2024-03-13 03:20 UTC, Vremold commented on compiler/dialects/lib/Dialect/Ccl/IR/CclOps.cpp
> +      if (isa<ccl::WaitOp>(user)) {
Please use stricter checks to require all users to be ccl.wait

2024-03-13 03:20 UTC, Vremold commented on compiler/dialects/lib/Dialect/Ccl/IR/CclOps.cpp
> +// A BroadcastOp with a synchronous of false plus a WaitOp equals a BroadcastOp
Refine this comment as this pattern is not only for broadcast op

2024-03-13 03:20 UTC, Vremold commented on compiler/dialects/lib/Dialect/Ccl/IR/CclOps.cpp
> +    auto cclOp = op.getSrc().getDefiningOp();
Please check whether its src is really a ccl.op.

2024-03-18 15:46 UTC, qingyunqu approved these changes
LGTM

2024-03-18 15:47 UTC, merged