[tf-frontend] convert repeat to tile + convert tf.round to mhlo.round
bytedance/byteir pull request #222
Opened 2024-04-27 09:26 UTC by heromapwrd

1. convert repeat to tile
2. set out batch size of repeat in a separate pass
3. convert tf.round to mhlo.round

2024-04-29 11:16 UTC, qingyunqu requested changes

2024-04-29 11:16 UTC, qingyunqu commented on frontends/tf-frontend/tf_mlir_ext/transforms/convert_repeat_to_tile.cc
> +mlir::tfext::createConvertRepeatToTilePass() {
Should add lit test for this pass?

2024-04-29 11:16 UTC, qingyunqu commented on frontends/tf-frontend/tf_mlir_ext/transforms/convert_repeat_to_tile.cc
> +mlir::tfext::createConvertRepeatToTilePass() {
same to other pass or pattern.

2024-04-30 01:18 UTC, heromapwrd commented on frontends/tf-frontend/tf_mlir_ext/transforms/convert_repeat_to_tile.cc
> +mlir::tfext::createConvertRepeatToTilePass() {
OK

2024-04-30 03:48 UTC, qingyunqu approved these changes
LGTM

2024-04-30 04:47 UTC, merged